/// Flutter icons PCParts
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PCParts
///      fonts:
///       - asset: fonts/PCParts.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PCParts {
  PCParts._();

  static const _kFontFam = 'PCParts';
  static const String _kFontPkg = null;

  static const IconData ssd = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cpu = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData case_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData supply = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocard = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData memory = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cooler = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData motherboard = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
